go:
    version: 1.15
repository:
    path: github.com/ubccr/prometheus-grendel-sd
build:
    binaries:
        - name: prometheus-grendel-sd
          path: .
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
